completed
Tylerlangsam/Pod1_repo pull request #81
Opened 2022-03-06 14:56 UTC by patrice17-20

I hope I did okay

2022-03-06 22:54 UTC, patrice17-20 commented
@Tylerlangsam ive updated the strings and lists challenge

2022-03-07 18:02 UTC, Tylerlangsam commented on Patrice/strings_and_lists_challenge.py
> +print(f{"joined_names + email})
This is incorrect syntax for an f-string, each variable needs to be in their own curly brackets

2022-03-07 18:02 UTC, Tylerlangsam requested changes
This is incorrect syntax for an f-string, each variable needs to be in their own curly brackets

2022-03-07 18:03 UTC, Tylerlangsam approved these changes

2022-03-07 18:04 UTC, Tylerlangsam approved these changes

2022-03-07 18:05 UTC, Tylerlangsam approved these changes

2022-03-07 18:05 UTC, merged